### ISSUE TITLE
.grid-item after .end-row should clear left

### ISSUE THREAD

**Issue by davidrleonard** [chimecms/chime-starter#5]
If you have mulitple rows of floated width-* elements, and one has a deeper height than expected, it can mess up the grid. For example:

```
<div class="grid-box">
  <div class="grid-item width-one-third"> ... REALLY LONG STUFF IN HERE! ... </div>
  <div class="grid-item width-one-third"> ... normal stuff ... </div>
  <div class="grid-item width-one-third end-row"> ... normal stuff ... </div>

  <div class="grid-item width-one-third"> ... normal stuff ... </div>
  <div class="grid-item width-one-third"> ... normal stuff ... </div>
  <div class="grid-item width-one-third end-row"> ... normal stuff ... </div>
</div>
```

![image](https://cloud.githubusercontent.com/assets/6456757/8121132/20d78656-105c-11e5-8e78-c4c443e4d881.png)

If you're manually specifying .end-row for your grid, this fixes it:
```
.end-row + .grid-item {
  clear: left;
}
```

Unless each row should get it's own grid-box? /cc @norrishung

**Comment by maya** [comment]
Would a min-height for the tallest grid-item solve this?

**Comment by norrishung** [comment]
@maya I agree! Ideally grid items should all be the same height defined by the tallest grid-item. 
@davidrleonard although it doesn't hurt to have this fix in here in the cases where grid-items aren't the same height. Thanks for the suggestion David!
